matrix:
  include:
    - name: linux-py27
      language: python
      python: 2.7
      sudo: required
      services:
        - docker
      env:
        - PIP=pip2.7
        - PYTHON=python2.7
        - CIBW_BUILD=cp27-*
        - TOXENV=py27

    - name: linux-py34
      language: python
      python: 3.4
      sudo: required
      services:
        - docker
      env:
        - PIP=pip3.4
        - PYTHON=python3.4
        - CIBW_BUILD=cp34-*
        - TOXENV=py34

    - name: linux-py35
      language: python
      python: 3.5
      sudo: required
      services:
        - docker
      env:
        - PIP=pip3.5
        - PYTHON=python3.5
        - CIBW_BUILD=cp35-*
        - TOXENV=py35

    - name: linux-py36
      language: python
      python: 3.6
      sudo: required
      services:
        - docker
      env:
        - PIP=pip3.6
        - PYTHON=python3.6
        - CIBW_BUILD=cp36-*
        - TOXENV=py36

    - name: linux-py37
      language: python
      python: 3.7
      dist: xenial
      sudo: required
      services:
        - docker
      env:
        - PIP=pip3.7
        - PYTHON=python3.7
        - CIBW_BUILD=cp37-*
        - TOXENV=py37

    - name: osx-py27
      os: osx
      language: generic
      env:
        - PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:$PATH"
        - PIP=pip2.7
        - PYTHON=python2.7
        - TOXENV=py27
        - CIBW_BUILD=cp27-*
        - CIBW_TEST_COMMAND="make -C {project} lint test"
        - CIBW_BEFORE_BUILD="${PIP} install -U pip; ${PIP} install flake8 tox"
      install:
        - ${PIP} install cibuildwheel==0.11.1
      script:
        - cibuildwheel --output-dir dist

    - name: osx-py34
      os: osx
      language: generic
      env:
        - PIP=pip3.4
        - PYTHON=python3.4
        - TOXENV=py34
        - CIBW_BUILD=cp34-*
        - CIBW_TEST_COMMAND="make -C {project} lint test"
        - CIBW_BEFORE_BUILD="${PIP} install -U pip; ${PIP} install flake8 tox"
      install:
        - ${PIP} install cibuildwheel==0.11.1
      script:
        - cibuildwheel --output-dir dist

    - name: osx-py35
      os: osx
      language: generic
      env:
        - PIP=pip3.5
        - PYTHON=python3.5
        - TOXENV=py35
        - CIBW_BUILD=cp35-*
        - CIBW_TEST_COMMAND="make -C {project} lint test"
        - CIBW_BEFORE_BUILD="${PIP} install -U pip; ${PIP} install flake8 tox"
      install:
        - ${PIP} install cibuildwheel==0.11.1
      script:
        - cibuildwheel --output-dir dist

    - name: osx-py36
      os: osx
      language: generic
      env:
        - PIP=pip3.6
        - PYTHON=python3.6
        - TOXENV=py36
        - CIBW_BUILD=cp36-*
        - CIBW_TEST_COMMAND="make -C {project} lint test"
        - CIBW_BEFORE_BUILD="${PIP} install -U pip; ${PIP} install flake8 tox"
      install:
        - ${PIP} install cibuildwheel==0.11.1
      script:
        - cibuildwheel --output-dir dist

    - name: osx-py37
      os: osx
      language: generic
      env:
        - PIP=pip3.7
        - PYTHON=python3.7
        - TOXENV=py37
        - CIBW_BUILD=cp37-*
        - CIBW_TEST_COMMAND="make -C {project} lint test"
        - CIBW_BEFORE_BUILD="${PIP} install -U pip; ${PIP} install flake8 tox"
      install:
        - ${PIP} install cibuildwheel==0.11.1
      script:
        - cibuildwheel --output-dir dist

install:
  - ${PIP} install -U pip
  - ${PIP} install flake8 tox
  - ${PIP} install cibuildwheel==0.11.1

script:
  - make lint
  - make test
  - git stash --all # Restore fresh checkout
  - cibuildwheel --output-dir wheelhouse
